default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: devco_platform_development

test:
  <<: *default
  database: devco_platform_test

production:
  <<: *default
  database: devco_platform_production
  username: devco_platform
  password: <%= ENV["DEVCO_PLATFORM_DATABASE_PASSWORD"] %>
